version: '3.4'
services:
  catalogdb:
    image: postgres:16

  basketdb:
    image: postgres:16

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
